services:
  server:
    build:
      context: ./back
    container_name: server
    working_dir: /app
    volumes:
      - ./back:/app
    command: python run.py
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/AREAdatabase
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
