version: '3.8'

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./back
    container_name: server
    working_dir: /app
    volumes:
      - ./back:/app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/AREAdatabase
    depends_on:
      - mongo

  client_mobile:
    build:
      context: ./front/mobile
    container_name: client_mobile
    working_dir: /app
    volumes:
      - ./front/mobile:/app

  client_web:
    build:
      context: ./front/web
    container_name: client_web
    working_dir: /app
    volumes:
      - ./front/web:/app
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - NODE_ENV=production
    depends_on:
      - server
      - client_mobile

volumes:
  mongo-data:
