name: area_front_mobile
description: Area | Front mobile
version: 0.0.0+1
repository: https://github.com/EpitechPromo2027/B-DEV-500-BDX-5-2-area-yohan.decamps
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

platforms:
  android:
  ios:

environment:
  flutter: 3.24.3
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_secure_storage: ^9.2.2
  flutter_translate: ^4.1.0
  font_awesome_flutter: ^10.7.0
  go_router: ^14.6.1
  http: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/i18n/
    - shared_assets/images/
  uses-material-design: true

flutter_launcher_icons:
  adaptive_icon_foreground: "shared_assets/images/icon.png"
  adaptive_icon_background: "#00000000"
  android: "launcher_icon"
  image_path: "shared_assets/images/icon.png"
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
