name: Back Build
run-name: ${{github.actor}} ${{github.branch}} | Back Build
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build with Docker Compose
        run: |
          docker-compose build server

      - name: Start services with Docker Compose
        run: |
          docker-compose up -d server

      - name: Check if backend is running
        run: |
          sleep 10
          curl -f http://localhost:8080/docs || exit 1

      - name: Shutdown services
        run: |
          docker-compose -f docker-compose.yml down
