name: Back Build
run-name: ${{github.actor}} ${{github.branch}} | Back Build
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27018:27017
        volumes:
          - mongo-data:/data/db
        options: --health-cmd "exit 0" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      - name: Remove existing mongo container
        run: |
          docker ps -a -q --filter "name=mongo" | xargs --no-run-if-empty docker rm -f

      - name: Build with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build

      - name: Start services with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Check if backend is running
        run: |
          sleep 10
          curl -f http://localhost:8080/docs || exit 1

      - name: Shutdown services
        run: |
          docker-compose -f docker-compose.yml down
