name: Front Web Build
run-name: ${{github.actor}} ${{github.branch}} | Front Web Build
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20.17.0"

      - name: Install dependencies
        run: npm install
        working-directory: ./front/web/app

      - name: Build project
        run: npm run build
        working-directory: ./front/web/app
