name: Front Mobile Build
run-name: ${{github.actor}} ${{github.branch}} | Front Mobile Build
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Create .env file
        run: |
          echo "API_URL=http://10.0.2.2:8080" > ./front/mobile/app/.env

      - name: Build with Docker Compose
        run: |
          docker-compose build client_mobile
