name: Front Web Build
run-name: ${{github.actor}} ${{github.branch}} | Front Web Build
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: create .env file
        run: |
          echo "API_URL=http://0.0.0.0:8080" > ./front/web/.env
          echo "PORT=8081" >> ./front/web/.env

      - name: Build with Docker Compose
        run: |
          docker-compose build client_mobile client_web_build client_web

      - name: Start services with Docker Compose
        run: |
          docker-compose up -d client_mobile client_web_build client_web && sleep 30

      - name: Check if front web is running
        run: |
          curl -f http://localhost:8081/login || exit 1

      - name: Shutdown services
        run: |
          docker-compose -f docker-compose.yml down
